#!/bin/bash

# Quit the script when the first command fails.
set -e -o pipefail -x

TAR=/bin/tar
CURL=/usr/bin/curl
BASENAME=/usr/bin/basename
BUNZIP2=/bin/bunzip2
GUNZIP=/bin/gunzip

URL="$1"
FILE=`"$BASENAME" "$URL"`
EXT="${FILE##*.}"
BASE="${FILE%.*}"
BBASE="${BASE%.*}"

if [ "$EXT" == "bz2" ]
then
  UNCOMPRESS="$BUNZIP2"
else
  UNCOMPRESS="$GUNZIP"
fi

if [ ! -e "$BBASE" ]
then
  echo "fetching $URL"
  "$CURL" --location --silent --show-error "$URL" | "$UNCOMPRESS" --stdout | "$TAR" xf - || echo "failed to fetch $URL"
else
  echo "skipping $URL because it was already fetched"
fi
